import Head from 'next/head';
import Image from 'next/image';

import Header from '@/components/Header';
import { About } from './About';
import { Introduction } from './Introduction';
import { Technologie } from './Technologie';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap"
					rel="stylesheet"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap"
					rel="stylesheet"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap"
					rel="stylesheet"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
					rel="stylesheet"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			<div id="App">
				<div className="homepage">
					<Header />
					<div className="homepage__overflow">
						<About />
						<Introduction />
						<Technologie />
					</div>
				</div>
			</div>
		</>
	);
}
